# Generated by Django 4.0 on 2022-07-28 14:04

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=sorl.thumbnail.fields.ImageField(null=True, upload_to='user_photos/%Y/%m/%d/'),
        ),
    ]
