# Generated by Django 4.0 on 2022-07-23 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custom_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.BooleanField()),
                ('is_confirmed', models.BooleanField(default=False)),
                ('elo_change', models.SmallIntegerField()),
                ('confirming_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_matches', to='custom_auth.user')),
                ('requesting_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='custom_auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requesting_player_score', models.PositiveSmallIntegerField()),
                ('confirming_player_score', models.PositiveSmallIntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='tennis.match')),
            ],
        ),
    ]
