# Generated by Django 4.0 on 2022-07-24 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Best of 1'), (3, 'Best of 3'), (5, 'Best of 5')], default=1),
            preserve_default=False,
        ),
    ]
