# Generated by Django 4.0 on 2022-08-03 08:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tennis', '0002_match_match_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
